# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: submission_process.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'submission_process.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18submission_process.proto\x12\x12submission_process\"M\n\x0eProcessRequest\x12*\n\x06status\x18\x01 \x01(\x0e\x32\x1a.submission_process.Status\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x11\n\x0fProcessResponse*n\n\x06Status\x12\x08\n\x04INFO\x10\x00\x12\x08\n\x04WARN\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\x0b\n\x07SUCCESS\x10\x03\x12\x0b\n\x07\x46\x41ILURE\x10\x04\x12\x0b\n\x07UNKNOWN\x10\x05\x12\x0b\n\x07VERDICT\x10\x06\x12\x11\n\rFINAL_VERDICT\x10\x07\x32{\n\x11SubmissionProcess\x12\x66\n\x17streamSubmissionProcess\x12\".submission_process.ProcessRequest\x1a#.submission_process.ProcessResponse\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'submission_process_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=146
  _globals['_STATUS']._serialized_end=256
  _globals['_PROCESSREQUEST']._serialized_start=48
  _globals['_PROCESSREQUEST']._serialized_end=125
  _globals['_PROCESSRESPONSE']._serialized_start=127
  _globals['_PROCESSRESPONSE']._serialized_end=144
  _globals['_SUBMISSIONPROCESS']._serialized_start=258
  _globals['_SUBMISSIONPROCESS']._serialized_end=381
# @@protoc_insertion_point(module_scope)
