services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./backend/codesirius:/app/codesirius
    working_dir: /app/codesirius
    command: >
      sh -c "mkdir -p /app/codesirius/logs && python manage.py runserver 0.0.0.0:8000"
    profiles:
      - production
    environment:
      - GITHUB_ACTIONS=${GITHUB_ACTIONS:-false}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14.15-alpine3.21
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - production

  email-consumer:
    build:
      context: consumers/email-consumer
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./consumers/email-consumer:/app
    working_dir: /app
    command: >
      sh -c "python3 main.py"
    profiles:
      - production

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - DEV=true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    working_dir: /app
    command: >
      sh -c  "npm run dev"
    profiles:
      - development

  frontend-prod:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - DEV=false
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    working_dir: /app
    command: >
      sh -c  "npm run build && npm run start"
    profiles:
      - production
      

  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    restart: unless-stopped
    profiles:
      - production

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    profiles:
      - production
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3001:3000"  # Grafana UI on port 3001 (default is 3000, but you can change it)
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"  # Set an admin password (default is 'admin')
    depends_on:
      loki:
        condition: service_healthy
    restart: unless-stopped
    profiles:
      - monitoring


  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config:/etc/loki/config
      - ./loki/data:/loki
    command: -config.file=/etc/loki/config/loki-config.yml
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3100/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    profiles:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail/config:/etc/promtail
      - ./backend/codesirius/logs:/logs
    command: -config.file=/etc/promtail/promtail.yml
    depends_on:
      loki:
        condition: service_healthy
    restart: unless-stopped
    profiles:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/config:/etc/prometheus
    ports:
      - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      loki:
        condition: service_healthy
    restart: unless-stopped
    profiles:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    profiles:
      - monitoring

volumes:
  postgres_data:
  grafana_data:
