services:
  backend:
    build:
        context: backend
        dockerfile: Dockerfile
        args:
          - DEV=true
    ports:
      - "8000:8000"
    volumes:
        - ./backend/codesirius:/app/codesirius
    working_dir: /app/codesirius
    command: >
        sh -c "python manage.py runserver 0.0.0.0:8000"
