services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./backend/codesirius:/app/codesirius
    working_dir: /app/codesirius
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=codesirius
      - DB_USER=codesirius
      - DB_PASSWORD=codesirius
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14.15-alpine3.21
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      # credentials are hardcoded as it is only for development
      POSTGRES_USER: codesirius
      POSTGRES_PASSWORD: codesirius
      POSTGRES_DB: codesirius
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U codesirius" ]
      interval: 10s
      timeout: 5s
      retries: 5



  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - DEV=true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules # to avoid overwriting node_modules
      - /app/.next  # to avoid overwriting .next
    working_dir: /app
    command: >
      sh -c  "npm run dev"

volumes:
  postgres_data:
      
