# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import reference_solution_consumer.ref_sol_validation_process_pb2 as ref__sol__validation__process__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ref_sol_validation_process_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RefSolValidationProcessStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.streamRefSolValidationProcess = channel.stream_unary(
                '/ref_sol_validation_process.RefSolValidationProcess/streamRefSolValidationProcess',
                request_serializer=ref__sol__validation__process__pb2.ProcessRequest.SerializeToString,
                response_deserializer=ref__sol__validation__process__pb2.ProcessResponse.FromString,
                _registered_method=True)


class RefSolValidationProcessServicer(object):
    """Missing associated documentation comment in .proto file."""

    def streamRefSolValidationProcess(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RefSolValidationProcessServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'streamRefSolValidationProcess': grpc.stream_unary_rpc_method_handler(
                    servicer.streamRefSolValidationProcess,
                    request_deserializer=ref__sol__validation__process__pb2.ProcessRequest.FromString,
                    response_serializer=ref__sol__validation__process__pb2.ProcessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ref_sol_validation_process.RefSolValidationProcess', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ref_sol_validation_process.RefSolValidationProcess', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RefSolValidationProcess(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def streamRefSolValidationProcess(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ref_sol_validation_process.RefSolValidationProcess/streamRefSolValidationProcess',
            ref__sol__validation__process__pb2.ProcessRequest.SerializeToString,
            ref__sol__validation__process__pb2.ProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
