# Generated by Django 5.1.5 on 2025-02-14 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="language",
            name="version",
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="language",
            constraint=models.UniqueConstraint(
                fields=("name", "version"), name="unique_language_name_version"
            ),
        ),
    ]
