# Generated by Django 5.1.5 on 2025-04-29 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0002_problem_difficulty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="user",
        ),
    ]
