# Generated by Django 5.1.5 on 2025-02-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0003_alter_language_name_alter_language_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
