# Generated by Django 5.1.5 on 2025-03-16 09:23

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0005_sampletest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sampletest",
            options={
                "verbose_name": "Sample Test",
                "verbose_name_plural": "Sample Tests",
            },
        ),
        migrations.AddField(
            model_name="sampletest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 3, 16, 9, 23, 22, 20341, tzinfo=datetime.timezone.utc
                ),
                help_text="The date and time this record was created.",
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sampletest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="sampletest",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time this record was last updated.",
                verbose_name="Updated at",
            ),
        ),
        migrations.AddField(
            model_name="sampletest",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who last updated this record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AlterField(
            model_name="executionconstraint",
            name="memory_limit",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(32),
                    django.core.validators.MaxValueValidator(1024),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="executionconstraint",
            name="time_limit",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sampletest",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sample_tests",
                to="problems.problem",
            ),
        ),
        migrations.CreateModel(
            name="HiddenTestBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this record was created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last updated.",
                        verbose_name="Updated at",
                    ),
                ),
                ("s3_path", models.CharField(max_length=1000)),
                ("test_count", models.PositiveIntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "problem",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hidden_test_bundle",
                        to="problems.problem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who last updated this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hidden Test Bundle",
                "verbose_name_plural": "Hidden Test Bundles",
            },
        ),
    ]
