---
name: Checks

on:
  push:
    branches:
      - dev
  pull_request:
    types:
        - opened
        - synchronize
        - reopened
    branches:
      - dev

jobs:
  backend-test-and-lint:

    services:
      db:
        image: postgres:14.15-alpine3.21
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        options: >
          --health-cmd "pg_isready -U ${{ secrets.DB_USER }}" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up environment variables
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the images
        run: docker compose build backend

      - name: Run the containers
        run: docker compose up -d backend

      - name: Run tests
        run: docker compose exec backend sh -c "python manage.py test"

      - name: Run linting
        run: docker compose exec backend sh -c "flake8 ."

      - name: Stop the containers
        run: |
          docker compose down backend
          docker compose down db

